import loot_table
descriptions = {
  "discord:national_flag_2020": "National_flag_2020 is obtainable by playing DiscordMC\non `9th Aug 2020`.\n7 Players have this item currently.",
  "discord:medal_of_contribution": "Medal_of_contribution is obtainable by suggesting an idea to DiscordMC.\n\nThe people who has it currently are:\n - GoldenDNA#1938\n - ylq#9769\n - TDB#1024",
  "discord:discordmc": "DiscordMC is a very fun game!(I think...)",
  "discord:wood": "Wood is obtainable by chopping.\nCan be crafted into:\n - wood_planks",
  "discord:wood_planks": "Wood planks are obtainable by crafting using wood.\nCan be crafted into:\n - stick\n - crafting_table",
  "discord:stick": "Sticks are obtainable by crafting using wood_planks.\nCan be crafted into all kinds of tools(pickaxe, axe, sword)",
  "discord:crafting_table": "Crafting_tables allow for certain 3x3 crafts in regular minecraft.",
  "discord:stone": "Stone is obtainable by mining with at least a wooden pickaxe.\nCan be crafted into stone tools.",
  "discord:iron": "Iron is obtainable by:\n - Mining with at least a stone pickaxe\n - Buried treasure\n - Pillager outpost\n - Desert Temple\n - Jungle Temple\n - Zombies\n\nCan be crafted into iron tools, iron_armor and iron_shield",
  "discord:diamond": "Diamond is obtainable by:\n - Mining with at least an iron pickaxe\n - Buried treasure\n - Desert temple\n - Jungle temple\n - Zombies\n\nCan be crafted into diamond tools, diamond_armor and diamond_shield.",
  "discord:emerald": "Emerald is obtainable by villages.\nCurrently has no functionality.",
  "discord:gold": "Gold is obtained by:\n - A mining rare drop in the nether.\n\tThere is a 20% chance of getting gold every 50000 secs.\n - Crafting using gold_nugget",
  "discord:gold_nugget": "Gold_nugget is obtainable by killing zombie_pigman in the nether.",
  "discord:obsidian": "Obsidian is obtainable by mining with at least a diamond pickaxe. \nCan be crafted into obsidian tools, obsidian_armor, obsidian_shield.\nIs part of the recipe of:\n - nether_portal\n - portal_table",
  "discord:lava": "Lava is a mining rare drop. There is a 1/2 chance of getting lava every 50000 secs.\nIs part of the recipe of:\n - nether_portal",
  "discord:netherite_scrap": "Netherite_scrap is obtainable by mining in the nether with at least an obsidian pickaxe.\nIs part of the recipe of:\n - netherite_ingot",
  "discord:portal_table": "Portal_table allow crafting of portals.",
  "discord:netherrack": "Netherrack is obtainable by mining in the nether with at least a wooden_pickaxe.\nCurrently has no functionality.",
  "discord:nether_quartz": "Nether_quartz is obtainable by mining in the nether with at least a wooden_pickaxe.\nCurrently has no functionality",
  "discord:magma_block": "Magma_block is obtainable by mining in the nether with at least a wooden_pickaxe.\nCurrently has no functionality.",
  "discord:netherite_ingot": "Netherite_ingot is crafted using gold and netherite_scrap.\nCan be used to craft netherite tools, netherite_sword and netherite_armor.",
  "discord:nether_portal": "Nether_portal allows access to the nether.",
  "discord:end_portal": "End_portal allows access to the_end.",
  "discord:end_stone": "End_stone is obtained by mining in the end with at least a stone_pickaxe.",
  "discord:chorus_seed": "Chorus_seed is obtained by mining in the end with at least a netherite_pickaxe.\nCan be crafted into chorus_fruit.",
  "discord:chorus_fruit": "Chorus_fruit is obtained by crafting using chorus_seed.\nCurrently has no functionality.",
  "discord:rotten_flesh": "Rotten_flesh is dropped by zombies. \nIs part of the recipe of undead_sword and undead_bow.",
  "discord:bone": "Bone is obtained by:\n - Killing skeletons\n - By hunting in the overworld\nIs part of the recipe of undead_sword and undead_bow.",
  "discord:string": "String is obtained by:\n - Killing spiders\n - Hunting in the nether\nIs part of the recipe of all bows.",
  "discord:gunpowder": "Gunpowder is dropped by creepers.\nIs part of the recipe of explosive_bow.",
  "discord:blaze_rod": "Blaze_rod is obtained by:\n - Killing blazes\n - Hunting in the nether\nCan be crafted into blaze_powder.",
  "discord:blaze_powder": "Blaze_bowder is crafted using blaze_rod.\nIs part of the recipe of eye_of_ender",
  "discord:ender_pearl": "Ender_pearl is obtained by:\n - Killing endermen\n - Hunting in the nether\nIs part of the recipe of eye_of_ender.",
  "discord:eye_of_ender": "Eye_of_ender is part of the crafting recipe of end_portal.",
  "discord:arrow": "Arrow is dropped from skeletons.\nCurrently has no functionality.",
  "discord:meat": "Meat is obtainable from hunting.\nYou start with 10 meat.\n\nEverytime you send a command, you lose 0.1 meat.",
  "discord:spider_eye": "Spider_eye is dropped by spiders.\nCurrently has no functionality.",
  "discord:magma_cream": "Magma cream is dropped by magma cubes in the nether.\nCurrently has no functionality.",
  "discord:tnt": "TNT is obtainable from desert_temples.\nCurrently has no functionality.",
  "discord:end_crystal": "End_crystal is  a mining rare drop. There is a 1/3 chance of getting end_crystal every 100000 seconds mining in the end with at least a netherite_pickaxe.\nCurrently has no functionality.",
  "discord:wooden_sword": "Wooden_sword deals {} damage.".format(loot_table.sword_multiplier['discord:wooden_sword']),
  "discord:stone_sword": "Stone_sword deals {} damage.".format(loot_table.sword_multiplier['discord:stone_sword']),
  "discord:iron_sword": "Iron_sword deals {} damage.".format(loot_table.sword_multiplier["discord:iron_sword"]),
  "discord:diamond_sword": "Diamond_sword deals {} damage.".format(loot_table.sword_multiplier['discord:diamond_sword']),
  "discord:obsidian_sword": "Obsidian_sword deals {} damage.".format(loot_table.sword_multiplier['discord:obsidian_sword']),
  "discord:undead_sword": "Undead_sword deals 2.5x damage to undead mobs.\n(regular: {}, undead: {})".format(loot_table.sword_multiplier['discord:undead_sword'], int(loot_table.sword_multiplier['discord:undead_sword'] * 2.5)), 
  "discord:netherite_sword": "Netherite_sword deals {} damage.".format(loot_table.sword_multiplier['discord:netherite_sword']),
  "discord:wooden_pickaxe": "Wooden_pickaxe allows the player to mine stone, netherrack, magma_block and nether_quartz",
  "discord:stone_pickaxe": "Stone_pickaxe allows the player to mine iron.",
  "discord:iron_pickaxe": "Iron_pickaxe allows the player to mine diamonds.",
  "discord:diamond_pickaxe": "Diamond_pickaxe allows the player to mine obsidian(and get lava).",
  "discord:obsidian_pickaxe": "Obsidian_pickaxe allows the player to mine netherite_scrap.",
  "discord:netherite_pickaxe": "Netherite_pickaxe allows the player to obtain end_crystal.",
  "discord:bow": "Bow deals {} damage.".format(loot_table.bow_multiplier['discord:bow']),
  "discord:undead_bow": "Undead_bow deals 1.5x more damage to undead mobs.\n(regular: {}, undead: {})".format(str(loot_table.bow_multiplier['discord:undead_bow']), str(int(loot_table.bow_multiplier["discord:undead_bow"] * 1.5))),
  "discord:explosive_bow": "Explosive_bow deals {} damage.".format(loot_table.bow_multiplier['discord:explosive_bow']),
  "discord:crossbow": "Crossbow deals {} damage.\nIt is obtained by exploring pillager_outposts.".format(str(loot_table.bow_multiplier["discord:crossbow"])), 
  "discord:iron_armor": "Iron_armor gives {} defense".format(loot_table.armor_multiplier['discord:iron_armor']), 
  "discord:diamond_armor": "Diamond armor gives {} defense".format(loot_table.armor_multiplier['discord:diamond_armor']), 
  "discord:obsidian_armor": "Obsidian armor gives {} defense".format(loot_table.armor_multiplier['discord:obsidian_armor']), 
  "discord:netherite_armor": "Netherite armor gives {} defense".format(loot_table.armor_multiplier["discord:netherite_armor"]),
  "discord:wool": "Wool is crafted using string.\nCan be crafted into:\n - Bed",
  "discord:bed": "Bed is crafted using string and wood_plank.\nCurrently has no functionality.", 
  "discord:first_5": "Be the first five players playing discordMC.",
  "discord:leather": "Leather is obtained by hunting in the overworld or nether.",
  "discord:stone_nerd": "Just flex your nerdy stone mining skills with this special item.", 
  "discord:wood_nerd": "Just flex your nerdy wood chopping skills with this special item.", 
  "discord:netherrack_nerd": "Just flex your nerdy netherrack mining skills with this item.", 
	"discord:enchanted_stick": "Enchanted stick to catch pets",
	"discord:nether_fortress": "A structure in the nether.\nHas a {}% chance of spawning.".format(str(loot_table.structure_chance['discord:nether']['discord:nether_fortress'] / 10)),
	"discord:bastion_remnant": "A structure in the nether.\nHas a {}% chance of spawning.".format(str(loot_table.structure_chance['discord:nether']['discord:bastion_remnant'] / 10)),
	"discord:village": "A structure in the overworld.\nHas a {}% chance of spawning.".format(str(loot_table.structure_chance['discord:overworld']['discord:village'] / 10)),
	"discord:dev_house": "A mysterious structure where it was rumoured that the devs lived in.",
	"discord:desert_temple": "A structure in the nether.\nHas a {}% chance of spawning.".format(str(loot_table.structure_chance['discord:overworld']['discord:desert_temple'] / 10)),
	"discord:jungle_temple": "A structure in the nether.\nHas a {}% chance of spawning.".format(str(loot_table.structure_chance['discord:overworld']['discord:jungle_temple'] / 10)),
	"discord:pillager_outpost": "A structure in the nether.\nHas a {}% chance of spawning.".format(str(loot_table.structure_chance['discord:overworld']['discord:pillager_outpost'] / 10)),
	"discord:buried_treasure": "A structure in the nether.\nHas a {}% chance of spawning.".format(str(loot_table.structure_chance['discord:overworld']['discord:buried_treasure'] / 10))
}
