default_call = "mc "

commands = "```" + str(default_call) + "start: Starts your profile``````" + str(default_call) + "chop: Start chopping wood``````" + str(default_call) + "collect_wood: Collect the wood that you chopped``````" + str(default_call) + "collect_mining: collect what you have mined``````" + str(default_call) + "inv: View your inventory``````" + str(default_call) + "craft <item>, <count>: Craft an item``````" + str(default_call) + "leave: Leave the game (Only for cowards and losers)``````" + str(default_call) + "hotbar: View your tools```" + "```" + str(default_call) + "dimension: View dimensions```" + "```" + str(default_call) + "warp: Warp to a different dimension``````" + str(default_call) + "explore : Explore your surroundings!```"

versions = [
  "```Version 0.1.0 [20 Jul 2020]: Initial Release``````Version 0.2.0 [20 Jul 2020]: Added 'chop' function, which gets you to chop wood``````Version 0.2.1 [20 Jul 2020]: Added 'collect_wood' and crafting recipies for wood_planks, crafting_table and sticks``````Version 0.3.0 [20 Jul 2020]: Added recipes for wooden_axe, which increases the amount of wood you collect``````Version 0.3.1 [20 Jul 2020]: Added recipes for wooden_pickaxe, haven't added 'mine' yet``````Version 0.4 [20 Jul 2020]: Added Mining, stone axe and stone pickaxe``````Version 0.5 [21 Jul 2020]: Added iron_pickaxe, iron_axe and diamonds, nerfed mining by 2x``````Version 0.5.1 [21 Jul 2020]: Added diamond_pickaxe``````Version 0.5.2 [21 Jul 2020]: Added diamond tools, fixed several crafting bugs``````Version 0.6.0 [22 Jul 2020]: More crafting recipes, and added modKick function for admins``````Version 0.7.0 [23 Jul 2020]: Added obsidian tools, fixed bugs and added lava``````Version 0.8.0 [27 Jul 2020]: Recoded crafting and changed mc inv command```",
  "```Version 1.0.0 [31 Jul 2020]: Added mob raids, bone, rotten_flesh and swords.``````Version 1.1.0 [2 Aug 2020]: Added Structures and mc explore``````Version 1.1.1 [3 Aug 2020]: Added Undead Sword``````Version 1.1.2 [4 Aug 2020]: Undead sword now deals 2.5x more damage against undead mobs.``````Version 1.2.0 [4 Aug 2020]: Added bow, crossbow(obtainable) and explosive bow/undead bow(un-obtainable)``````Version 1.2.1 [5 Aug 2020]: Fixed mc mine, mc hunt and mc chop``````Version 1.2.2 [6 Aug 2020]: Undead bows and Explosive Bows are now obtainable.``````Version 1.2.3 [7 Aug 2020]: Added bows to mc hotbar``````Version 1.3.0 [7 Aug 2020]: Added mc viewrecipe <recipe>``````Version 1.4.0 [8 Aug 2020]: Added portal table, magma, netherite scrap, gold, netherite ingot and mc dimension``````Version 1.4.1 [8 Aug 2020]: Added nether_portal, mc warp``````Version 1.4.2 [8 Aug 2020]: You can now warp back to the overworld``````Version 1.4.3 [8 Aug 2020]: Added enderman, blaze powder, eye of ender, netherite tools and netherite_armor``````Version 1.5.0 [8 Aug 2020]: Now you get 10% more items when you collect mining in the DiscordMC server!``````Version 1.6.0 [8 Aug 2020]: mc info <item> added.``````Version 1.6.1 [9 Aug 2020]: SG55 Speical! Added national_flag_2020! It is obtainable only on 9 Aug!``````Version 1.6.2 [9 Aug 2020]: Fixed Hunting Display Bugs``````Version 1.7.0 [9 Aug 2020]: Added the_end, end_portal, end_stone, chorus_seed and chorus_fruit``````Version 1.7.1 [10 Aug 2020]: Added gold_nugget and the crafting recipe to gold``````Version 1.7.2 [10 Aug 2020]: Added wool and beds (currently no function)``````Version 1.7.3 [10 Aug 2020]: Added wither_skull, magma_cream, wither_skeleton and magma_cube.``````Version 1.8.0 [10 Aug 2020]: Fixed crafting negative items, added the special item \"first_5\"``````Version 1.8.1 [10 Aug 2020]: Removed the fixed chances for death in \"mc explore\"```",
	"```Version 1.8.2 [10 Aug 2020]: Added nerd items (special rarity), which can be crafted using 1 million of an item``````Version 1.8.3 [10 Aug 2020]: Buffed treasure loot but increased the chance for you to die.``````Version 1.9.0 [10 Aug 2020]: Added bastion_remnant and nether_fortress.```",
  "```Version 2.0.0 [11 Aug 2020]: Added mc wardrobe, mc equip <slot>``````Version 2.0.1 [12 Aug 2020]: Buffed chances of wither_skull, added eye_of_ender to bastion_remnant's loot, buffed chances of mobs.``````Version 2.0.2 [13 Aug 2020]: Portals now have a 5% chance to break on use .``````Version 2.1.0 [13 Aug 2020]: Added different hunting loot tables for different dimensions and added leather``````Version 2.2.0 [13 Aug 2020]: Added mc inv <page>``````Version 2.2.1 [14 Aug 2020]: Fixed dying(DiscordMC Kool Kahoot)``````Version 2.2.2 [14 Aug 2020]: Added test command mc convert_to_roman and convert_to_integer.``````Version 2.2.3 [14 Aug 2020]: Added Enchanted Stick``````Version 2.3.0 [20 Aug 2020]: Added item IDs and shortened save files.``````Version 2.3.1 [23 Aug 2020]: Added wither_skull(ID: 50), sugar_cane(ID: 51) and nether_wart(ID: 52)``````Version 2.3.2 [23 Aug 2020]: Fixed mc collect_wood, mc collect_mining and mc collect_hunting. ```"
]
